# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 04b56fdaf0d6d95faad2086dbb0e5850efc256c91dc3633da56e2df74efb233224741b8e3eb94b026c8d1499e1f1ccc304bed4f5ebe937f4ac6587e347e0e686

test:
  secret_key_base: a35c40ec384d5408a2e22c1b39fb249e94a86821d2c9a724888b3a0539082ed000f810a38cfaac5eaa1824efbf067044b2698101b9455c96a4fa113c3b7dcdba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
